sudo: false
language: python
python:
  - 3.6
env:
  - SECRET_KEY="wl}^RKh6V_2!iPiFum#e"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install Flask-Testing
  - pip install coverage
  - pip install codecov
script:
  - coverage run -m pytest tests.py
  - codecov --token=daf8baef-fc96-41da-a404-6a44430114c2
